### ISSUE TITLE
Error while running on IOS but working on android 

### ISSUE THREAD

**Issue by Kimsoer** [451518849/epub_kitty#9]
=>I got this message error when i run debug it on iOS
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel com.xiaofwang.epub_kitty/page:
MissingPluginException(No implementation found for method listen on channel com.xiaofwang.epub_kitty/page)

-----------------------------------------------
=>Full error showing:

Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Running Xcode build...
Xcode build done.                                           35.8s
Syncing files to device iPhone 11 Pro Max...
flutter: /Users/codeclansdev/Library/Developer/CoreSimulator/Devices/F9A476B8-7791-4AE7-A0B6-FFF25B1EABCA/data/Containers/Data/Application/509A308F-A096-4DAC-894F-9109675B9A83/Library/Caches

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel com.xiaofwang.epub_kitty/page:
MissingPluginException(No implementation found for method listen on channel com.xiaofwang.epub_kitty/page)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by 451518849** [comment]
are you sure it install correctly? the problem is MissingPluginException. check it please.
